### PR TITLE
Dedupe surrogate gossip

### LINKED ISSUE #65: surrogateGossiper can form a feedback loop
If we have at least 3 peers which do not implement a particular channel, and some other peer sends gossip on that channel, then the following happens:

1. `Router.handleGossip()` decodes the message and calls `gossipChannel.deliver()`
2. `gossipChannel.deliver()` calls `surrogateGossiper.OnGossip()` with the incoming message
3. `surrogateGossiper.OnGossip` returns a `surrogateGossipData` with the same payload
4. `gossipChannel.deliver()` then relays this payload to other listeners
5. repeat

This surfaced as an error message from Weave Net "connection shutting down due to error: host clock skew of -4043s exceeds 900s limit", reported at https://groups.google.com/a/weave.works/forum/#!topic/weave-users/zcrATGRTY6s

It is quite bad because the peers are sending gossip data in a tight loop.

### PR DESCRIPTION
**Pull request by bboreham**
Fixes #65

### CODE REVIEW

File: surrogate_gossiper.go [hunk 1]
```diff
@@ -40,10 +42,13 @@ func (*surrogateGossiper) Gossip() GossipData {
 // OnGossip should return "everything new I've just learnt".
 // surrogateGossiper doesn't understand the content of messages, but it can eliminate simple duplicates
 func (s *surrogateGossiper) OnGossip(update []byte) (GossipData, error) {
+	hash := fnv.New64a()
+	hash.Write(update)
+	updateHash := hash.Sum64()
```
Comment (marccarre) [inline surrogate_gossiper.go]: LGTM: given how the FNV hash function works, and that we compute the hash once and then re-use it in the loop, this should reduce run time complexity from `O(n^2.m)` to `O(n^2+m)` which is good for long messages.

**Comment by marccarre** [comment]
As discussed previously on this issue and offline, 

* we can optimise further later, 
* the problem we are trying to solve is effectively having a "concurrent cache with a time-based eviction policy".

Other possible improvements would be to also allow the client application to: 

1. dependency-inject the TTL (time-to-live) of cache entries, 
2. dependency-inject the size and/or memory-footprint of such a cache in order to cap it;

This could maybe be useful depending on where and how mesh is used, as currently 1. is hard-coded, and 2. is not set, effectively allowing the cache to grow indefinitely.
